### ISSUE TITLE
TypeError: mask must be numpy array type

### ISSUE THREAD

**Issue by wanyiying** [hehe851/lung-segmentation#1]
运行时出现的问题：
`Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 427, in <module>
    history = fit(epoch, model, train_loader, val_loader, criterion, optimizer, sched)
  File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 275, in fit
    for i, data in enumerate(tqdm(train_loader)):
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\tqdm\notebook.py", line 259, in __iter__
    for obj in it:
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 94, in __getitem__
    aug = self.transform(image=img, mask=mask)
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\albumentations\core\composition.py", line 190, in __call__
    self._check_args(**data)
  File "D:\Anaconda3\envs\momo_1\lib\site-packages\albumentations\core\composition.py", line 267, in _check_args
    raise TypeError("{} must be numpy array type".format(data_name))
TypeError: mask must be numpy array type`
请问TypeError是不是由于albumentations版本的问题呢？

**Comment by xiaoyu955** [comment]
应该不是，可能是数据导入时出错了，看下标签图像有没有转化为numpy，在错的那一行代码之前print出来，看mask是什么类型




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoyu955/lung-segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月10日(星期五) 晚上6:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaoyu955/lung-segmentation] Question (Issue #1)





 
运行时出现的问题：
 Traceback (most recent call last): File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 427, in <module&gt; history = fit(epoch, model, train_loader, val_loader, criterion, optimizer, sched) File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 275, in fit for i, data in enumerate(tqdm(train_loader)): File "D:\Anaconda3\envs\momo_1\lib\site-packages\tqdm\notebook.py", line 259, in __iter__ for obj in it: File "D:\Anaconda3\envs\momo_1\lib\site-packages\tqdm\std.py", line 1195, in __iter__ for obj in iterable: File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__ data = self._next_data() File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data data = self._dataset_fetcher.fetch(index)  # may raise StopIteration File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda3\envs\momo_1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp&gt; data = [self.dataset[idx] for idx in possibly_batched_index] File "D:/PycharmProjects/pythonProject1/lung-segmentation-main/main.py", line 94, in __getitem__ aug = self.transform(image=img, mask=mask) File "D:\Anaconda3\envs\momo_1\lib\site-packages\albumentations\core\composition.py", line 190, in __call__ self._check_args(**data) File "D:\Anaconda3\envs\momo_1\lib\site-packages\albumentations\core\composition.py", line 267, in _check_args raise TypeError("{} must be numpy array type".format(data_name)) TypeError: mask must be numpy array type
 请问TypeError是不是由于albumentations版本的问题呢？
